### PR TITLE
Immplement material API endpoints

### PR DESCRIPTION
**Pull request by Federlizer**
This PR will implement Material's API endpoints. More functionality was added to the `Server.MaterialController` as well in order to keep the validation in the same layer. Namely, Create method now validates the data and there is an extra Update method that will also validate data and do the update, so that the Api controller doesn't have to do much of the business logic.

### CODE REVIEW

**Comment by ignaczalexander** [comment]
When trying to consume the material API I found a few difficulties.
If we want to create a material, we have to pass a MaterialType, which consists of a TypeId and Type. The problem is the server only accepts already existing material types and there's no way to create one from the API. The same applies to MaterialSubjects I think.

**Comment by Federlizer** [comment]
Well, yeah. I was left with the impression that this is how we're supposed to make it, i.e. we predefine the MaterialTypes and MaterialSubjects so that there are no duplicates. Another option is to create new ones as we stumble upon them. So when a new material is created, we still check if the MaterialType exists, if it doesn't it creates it. I can implement that if you think this is a better idea.

**Comment by ignaczalexander** [comment]
Yes, if we populate the DB with predefined material types and subjects that's gonna work but then it would be nice to be able to fetch them, so we can create a dropdown on the website.
Also, when creating a Material it looks like the Authors also must exist, maybe the server could handle checking the authors and creating one if it doesn't exist yet.

**Comment by Federlizer** [comment]
Yeah, fair enough. Didn't think about fetching MaterialTypes and MaterialSubjects. I'll implement that.

Also I'll make sure that if author doesn't exist, it'll be created. :+1:

**Comment by ignaczalexander** [comment]
Awesome 👍

**Comment by Derasm** [comment]
Merging the commit. It looks good.

**Pull request merged**
